spring.application.name=celebrarcatalog

spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:postgresql://localhost:5432/celebrarcatalog
spring.datasource.username=celebrarcatalog
spring.datasource.password=celebrarcatalog
